from typing import Any, Dict

from ai_engine.reasoning.llm_engine import LLMEngine
from ai_engine.reasoning.prompts import decision_prompt


class DecisionEngine:
    """Core reasoning engine for generating architectural decisions from requirements and context."""

    def __init__(self) -> None:
        """Initialize LLM Engine instance."""
        self.llm = LLMEngine()

    def decide(self, requirements: str, context: str) -> Dict[str, Any]:
        """Execute decision reasoning prompt and return structured decision dict.

        Args:
            requirements (str): High-level system requirements.
            context (str): Retrieved context documents from knowledge base.

        Returns:
            Dict[str, Any]: Dictionary containing architecture, tradeoffs, recommendation, and confidence.
        """
        prompt = decision_prompt(requirements, context)
        raw_output = self.llm.generate(prompt)

        parsed = self._parse_sections(raw_output)

        architecture = (
            parsed.get("Recommended Architecture") or raw_output
        )
        tradeoffs = (
            parsed.get("Trade-offs")
            or parsed.get("Key Trade-offs")
            or "Trade-off analysis included in decision output."
        )
        recommendation = (
            parsed.get("Final Recommendation")
            or parsed.get("Executive Summary")
            or raw_output
        )

        return {
            "architecture": architecture,
            "tradeoffs": tradeoffs,
            "recommendation": recommendation,
            "confidence": 1.0,
        }

    # TODO:
    # Replace markdown parsing with structured JSON output once
    # the LLM is configured to return JSON responses.
    def _parse_sections(self, text: str) -> Dict[str, str]:
        """Extract markdown header sections from generated LLM text.

        Args:
            text (str): Markdown response text generated by LLM.

        Returns:
            Dict[str, str]: Section header mapping to section content.
        """
        sections: Dict[str, str] = {}
        current_section = None
        lines = []

        for line in text.splitlines():
            if line.startswith("## "):
                if current_section:
                    sections[current_section] = "\n".join(lines).strip()
                current_section = line[3:].strip()
                lines = []
            else:
                lines.append(line)

        if current_section:
            sections[current_section] = "\n".join(lines).strip()

        return sections