from typing import Any, Dict

from ai_engine.reasoning.llm_engine import LLMEngine
from ai_engine.reasoning.prompts import decision_prompt


class DecisionEngine:
    """Core reasoning engine for generating architectural decisions from requirements and context."""

    def __init__(self) -> None:
        """Initialize LLM Engine instance."""
        self.llm = LLMEngine()

    def decide(self, requirements: str, context: str) -> Dict[str, Any]:
        """Execute decision reasoning prompt and return structured decision dict.

        Args:
            requirements (str): High-level system requirements.
            context (str): Retrieved context documents from knowledge base.

        Returns:
            Dict[str, Any]: Dictionary containing architecture, tradeoffs, recommendation, and confidence.
        """
        prompt = decision_prompt(requirements, context)
        raw_output = self.llm.generate(prompt)

        parsed = self._parse_sections(raw_output)

        architecture = self._get_section(
            parsed, "Recommended Architecture", "Architecture"
        )

        tradeoffs = self._get_section(
            parsed, "Trade-offs", "Tradeoffs", "Key Trade-offs", "Key Tradeoffs"
        )

        recommendation = self._get_section(
            parsed, "Final Recommendation", "Executive Summary", "Recommendation"
        )

        return {
            "architecture": architecture,
            "tradeoffs": tradeoffs,
            "recommendation": recommendation,
            "confidence": 1.0,
        }

    # TODO:
    # Replace markdown parsing with structured JSON output once
    # the LLM is configured to return JSON responses.
    def _parse_sections(self, text: str) -> Dict[str, str]:
        """Extract markdown header sections from generated LLM text.

        Handles variations in markdown heading styles (e.g. ##, ###, **##, #, etc.).

        Args:
            text (str): Markdown response text generated by LLM.

        Returns:
            Dict[str, str]: Section header mapping to section content.
        """
        sections: Dict[str, str] = {}
        current_section = None
        lines = []

        for raw_line in text.splitlines():
            line = raw_line.strip()
            # Strip markdown formatting markers to inspect line structure
            unwrapped = line.replace("*", "").replace("_", "").strip()

            is_header = False
            header_title = None

            if unwrapped.startswith("#"):
                is_header = True
                header_title = (
                    unwrapped.lstrip("#")
                    .strip()
                    .lstrip("0123456789.")
                    .strip()
                    .rstrip(":")
                )

            if is_header and header_title:
                if current_section:
                    sections[current_section] = "\n".join(lines).strip()
                current_section = header_title
                lines = []
            else:
                lines.append(raw_line)

        if current_section:
            sections[current_section] = "\n".join(lines).strip()

        return sections

    def _normalize_header(self, text: str) -> str:
        """Normalize header string by lowering, removing spaces, underscores, and all unicode hyphen/dash variants."""
        res = text.lower().replace(" ", "").replace("_", "")
        for hyphen in ["-", "‑", "–", "—", "‐", "‒", "―", "−"]:
            res = res.replace(hyphen, "")
        return res

    def _get_section(self, sections: Dict[str, str], *keys: str) -> str:
        """Retrieve section content matching candidate keys case-insensitively with partial matching support.

        Args:
            sections (Dict[str, str]): Parsed section dictionary.
            *keys (str): Candidate section header names.

        Returns:
            str: Matching section content string or empty string if not found.
        """
        # 1. Exact normalized match
        normalized_map = {
            self._normalize_header(k): v
            for k, v in sections.items()
        }
        for key in keys:
            norm_key = self._normalize_header(key)
            if norm_key in normalized_map and normalized_map[norm_key]:
                return normalized_map[norm_key]

        # 2. Partial keyword match (e.g., 'keytradeoffs&selectionrationale' matching 'keytradeoffs' or 'tradeoffs')
        for raw_k, v in sections.items():
            k_clean = self._normalize_header(raw_k)
            for key in keys:
                norm_key = self._normalize_header(key)
                if norm_key in k_clean or k_clean.startswith(norm_key):
                    if v:
                        return v
        return ""